function getDeck(exts) {
	console.log(exts);
	var e = exts.split(',');
	var blackCards = [];
	var whiteCards = [];
	for (var i = 0; i < e.length; i++) {
		switch(e[i]) {
			case 'base':
				blackCards = blackCards.concat(black());
				whiteCards = whiteCards.concat(white());
				break;
			case 'ext1':
				blackCards = blackCards.concat(exp1Black());
				whiteCards = whiteCards.concat(exp1White());
				break;
		}
	}
	return { black: blackCards, white: whiteCards };
}

function black() {
	return [
	{q: "__________ + __________ = __________.", draw: 3},
	{q: "Si, ho ucciso __________ Ti domandi come? __________", draw: 2},
	{q: "E il premio Oscar per __________ va a __________", draw: 2},
	{q: "Per il mio prossimo numero tirerò fuori __________ da __________", draw: 2},
	{q: "Passo 1: __________ Passo 2: __________ Passo 3: Guadagno!", draw: 2},
	{q: "Mentre ero sotto gli effetti di acidi,  __________ si trasformò in __________", draw: 2},
	{q: "__________ è una tendenza pericolosa che porta a __________", draw: 2},
	{q: "In un mondo depredato da __________ il nostro unico conforto è __________", draw: 2},
	{q: "Nel nuovo film di Shyamalan Bruce Willis scopre che __________ era invece __________ per tutto il tempo.", draw: 2},
	{q: "Non avevo veramente compreso __________ finché non incontrai __________", draw: 2},
	{q: "Voci dicono che il piatto preferito di Vladimir Putin è __________ ripieno di __________", draw: 2},
	{q: "LA7D presenta __________la storia di __________", draw: 2},
	"La nuova norma sulla sicurezza ora proibisce __________ sugli aerei. ",
	"È un peccato che i ragazzini al giorno d\'oggi partecipino a __________ ",
	"Fra 1.000 anni, quando le banconote saranno soltanto un ricordo lontano, __________ sarà il nostro denaro. ",
	"La lega serie A ha vietato __________ poiché dà un vantaggio ingiusto ai giocatori. ",
	"Qual è il vizio segreto di Batman? ",
	"Il prossimo romanzo di J.K.Rowling. Harry Potter e la camera dei __________ ",
	"Prof. mi dispiace ma non ho potuto finire i compiti per colpa di __________ ",
	"Cosa ho portato dal Messico? ",
	"__________? ",
	"C\'è un app per quello. ",
	"__________ Scommetto che non ne desideri soltanto uno! ",
	"Qual è il mio antidroga? ",
	"Mentre gli USA e la Russia gareggiavano per la conquista della Luna, il Messico ha investito milioni di pesos in __________  ",
	"Nel nuovo film della Disney, Hannah Montana si scontra per la prima volta contro ",
	"__________ ",
	"Qual è il mio potere segreto? ",
	"Qual è la nuova dieta del momento? ",
	"Cosa si mangia Vin Diesel per cena? ",
	"Quando il faraone rimase impassibile, Mosè scateno la piaga __________ ",
	"Come faccio a mantenere la mia attuale relazione? ",
	"Qual è la cosa più incrostata? ",
	"Nel carcere di Los Angeles le voci dicono che puoi scambiare 200 sigarette per __________ ",
	"Dopo il terremoto Sean Penn portò __________ alle persone di Haiti. ",
	"Invece del carbone la Befana ora porta ai bambini cattivi __________ ",
	"La vita degli indiani d\'America cambiò per sempre quando gli uomini bianchi Ii introdussero a __________ ",
	"Cosa usano gli insegnanti per ispirare al successo i ragazzi? ",
	"Amaro Montenegro. Sapore di __________ ",
	"Negli ultimi istanti di vita di Michael Jackson lui pensò a __________ ",
	"Ai neri piace __________ ",
	"Perché ho male ovunque? ",
	"Una romantica cena a lume di candela è incompleta senza __________ ",
	"Cosa posso andare a prendere dal passato per convincere la gente di essere un potente stregone? ",
	"Sono Valerio Staffelli e sono qui per parlavi di __________ ",
	"La gita scolastica fu completamente rovinata da __________ ",
	"Qual è il miglior amico di una ragazza? ",
	"Cara TopGirl, ho difficoltà con __________ e vorrei qualche consiglio. ",
	"Quando sarò il capo del governo creerò il Ministero del __________ ",
	"Cosa mi stanno nascondendo i miei genitori? ",
	"Cosa non fallisce mai nel ravvivare una festa? ",
	"Cosa migliora con l\'età? ",
	"__________ buono fino all\'ultima goccia. ",
	"Ho un sacco di problemi ma __________ non è fra questi. ",
	"__________ è una trappola! ",
	"Il nuovo reality show di MTV presenterà otto celebrità sull\'orlo dello sfinimento che vivranno con __________ ",
	"Cos\'è che mia nonna troverebbe allarmante ma nello stesso tempo anche stranamente affascinante? ",
	"Chi è il più emo? ",
	"Durante il sesso mi piace pensare a __________ ",
	"Cosa fece finire la mia passata relazione? ",
	"Cos\'è questo suono? ",
	"__________ Così è come voglio morire! ",
	"Perché sono appiccicoso? ",
	"Quale sarà il prossimo giocattolo dell\'Happy Meal? ",
	"Cosa sarà disponibile a volontà in paradiso? ",
	"Non so con che armi sarà combattuta la terza guerra mondiale. Ma nella quarta si useranno __________ ",
	"Cosa ti permette di portarti a letto, con assoluta certezza, una ragazza? ",
	"__________: testato dai bambini, approvato dalle madri. ",
	"Perché non riesco a dormire? ",
	"Cos\'è questo odore? ",
	"Cosa aiuterebbe Monti a rilassarsi? ",
	"Questo è come il mondo finirà, non con una esplosione ma con __________ ",
	"In arrivo a Broadway quest\'anno, __________: il musical. ",
	"Gli antropologi hanno recentemente scoperto un\'antica tribù che venera __________ ",
	"Ma prima che la uccida Signor Bond le voglio mostrare __________ ",
	"Recenti studi hanno mostrato che topi di laboratorio impiegano il 50\% in meno per uscire da un labirinto se sono stati esposti a __________  ",
	"Quale sarà la prossima coppia di supereroi? ",
	"Prossimamente su Rai Sport 2: i mondiali di __________ ",
	"Quando sarò milionario erigerò una statua di 30 metri per commemorare __________ ",
	"Nel tentativo di attrarre nuove persone, il museo nazionale di Storia Naturale inaugurerà una mostra interattiva su __________  ",
	"Guerra! A cosa ci serve? ",
	"Cosa mi crea flatulenze incontrollabili? ",
	"Di cosa odorano le persone anziane? ",
	"A cosa rinuncio per la quaresima? ",
	"La medicina alternativa sta ora adottando i poteri curativi di __________ ",
	"Quale cosa l\'Italia ha paracadutato ai bambini afghani? ",
	"Cosa piace a Silvio Berlusconi? ",
	"Durante il trascurato Periodo Marrone, Picasso ha prodotto centinai di quadri su __________ ",
	"Cosa non vuoi trovare nel tuo cibo cinese? ",
	"Bevo per dimenticare __________ ",
	"__________ Dammi un cinque fratello! ",
	];
}

function exp1Black(){
	return[
	{q: "Mors tua, vita mea. __________ tua, vita __________" , draw: 2},
	{q: "Benvenuti nella terra di __________ dove potrete ammirare __________ allo stato brado!" , draw: 2},
	{q: "Ogni volta che ascolto in tv la voce di __________ mi vien voglia di __________" , draw: 2},
	{q: "A proposito di __________, per me la soluzione è __________" , draw: 2},
	{q: "L\'altra sera mentre portavo a spasso il cane, ho visto __________ che con aria sospetta stava per __________" , draw: 2},
	{q: "Oggi __________ mi sembra davvero molto__________" , draw: 2},
	{q: "A __________ quando è in bagno, piace pensare a __________" , draw: 2},
	{q: "Walt Disney presenta __________ un nuovo cartoon che parla di __________" , draw: 2},
	{q: "Un__________ al giorno leva __________ di torno!" , draw: 2},
	{q: "Vorrei __________ per conquistare __________" , draw: 2},
	{q: "C\'è crisi, si torna al baratto: __________ per __________." , draw: 2},
	{q: "Il mio sogno ricorrente: __________ che __________." , draw: 2},
	{q: "L\'assenza di __________ è un evidente sintomo di __________" , draw: 2},
	"Arricchisciti rapidamente con __________",
	"__________ è la radice di tutti i mali del mondo!",
	"Il video della canzone \"YMCA\" fu registrato dai VillagePepole vestiti  da marinaio, pompiere, indiano e __________",
	"Era una notte buia e tempestosa. Ad un tratto la porta sbattè e __________",
	"KEEP CALM AND __________",
	"L\'Italia è fallita! Non ci sono più soldi. Adesso non mi resta che __________",
	"Salendo in soffitta ho aperto l\'antico baule di mia nonna e al suo interno ho trovato __________",
	"E\' il mio primo volo in aereo, ma il passeggero seduto accanto a me __________",
	"Ciao, sono Silvio Berlusconi e quando verrò eletto restituirò __________",
	"Caro Babbo Natale, quest\'anno in regalo vorrei __________",
	"Amore mio, sono qui in ginocchio davanti a te per __________",
	"Non so __________, ora cerco come si fa su youtube!",
	"Il mio primo pensiero al mattino è __________",
	"Piuttosto che andare dalla suocera, preferisco __________",
	"Oggi ti vedo strano, non ti senti bene? Non è che hai mangiato __________",
	"A __________ quando è in bagno, piace pensare a __________",
	"Prova il nuovo philadelphia al gusto di __________",
	"Quando aprì il vaso, Pandora vi trovò un\'unica cosa: __________",
	"Dlin dlon, un addetto pulizie al reparto __________",
	"Il peggior regalo di natale mai avuto da bambino è stato __________",
	"Rocco Siffredi nel tempo libero colleziona __________",
	"Mamma/papà come nascono i bambini? Come gli rispondi? __________",
	"Stai facendo sesso selvaggio e succede che __________",
	"Il 1930 è spesso indicato come l\'età d\'oro del __________",
	"La verità è che alla fine dell\'universo c\'è soltanto __________",
	"E\' ampiamente diffusa l\'idea che i nostri antenati non si sarebbero mai evoluti senza __________",
	"Ho un\'idea vincente per un nuovo programma tv. __________",
	"La ricetta del successo. __________",
	"Qual è la nuova dieta del momento? __________",
	"Un\'invenzione che potrebbe salvare il mondo. __________",
	"Vieni sorpreso da un temporale, per non bagnarti ti rifugi __________",
	"Uccidi i tuoi nemici con __________",
	"Al primo appuntamento ti presenti con? __________",
	"Primo classificato: __________",
	"La mia ultima frase sul letto di morte sarebbe: __________",
	"__________ non così che vi fate male!",
	"Avevo un piano perfetto, ma non avevo considerato __________.",
	"__________. Così è la vita!",
	"Quale sarà la nostra ultima speranza quando un nuovo Demone-Robot invaderà il mondo?",
	"Quando ho visto tua madre nuda, mi ha ricordato __________",
	"Hanno appena trovato un __________ nei rifiuti dell\'ospedale di Napoli.",
	"Adoro l\'odore di __________ la mattina.",
	"In realtà l\'11 settembre fu organizzato da __________",
	"Il Sacro Graal descritto nella Bibbia in realtà non è un calice ma è __________",
	"La felicità è __________",
	"Che ore sono? E\' l\'ora di__________!",
	"La nonna mi diceva sempre che __________, mi avrebbe reso cieco!",
	"__________ è l\'ottavo peccato capitale!",
	"Il dottore mi ha comunicato con faccia severa che il mio era un grave caso di __________",
	"Mi prodigherei in un ricco pompino soltanto per __________",
	"Baci il rospo ma, invece di trasformarsi in un principe, diventa __________",
	"La più grande disavventura che può capitare a una donna è __________",
	"Mamma mamma perchè papà indossa le scarpe col tacco 12?",
	"Obama ha un tatuaggio nascosto che raffigura __________",
	"Cos\'hai fatto l\'estate scorsa?",
	"Sei simpatico come __________",
	"Questa bibita energetica ha un sapore di __________",
	"Rimedi naturali per combattere l\'aerofagia: __________",
	"Dopo 10 anni di fidanzamento ti lascia con due semplici parole: sono omosessuale. La tua reazione è __________",
	];
}


function white() {
	return [ 
	"Una maledizione di un Gitano",
	"Un momento di silenzio",
	"Un festival della salsiccia",
	"Un poliziotto onesto che non ha niente da perdere",
	"Carestia",
	"Batteri Mangia-Carne",
	"Serpenti volanti che fanno sesso",
	"Non fregarsene un cazzo del Terzo Mondo",
	"Sexting",
	"Benny Benassi",
	"Pornostar",
	"Stupro e Saccheggio",
	"72 vergini",
	"Sparatoria da auto in corsa",
	"Un paradosso da viaggio nel tempo",
	"Cucina autentica messicana",
	"Gioielli da rapper",
	"Consulente",
	"Oberato dai debiti",
	"Problemi col babbo",
	"Avere l\'approvazione di Lapo Elkan",
	"Far cadere un lampadario sopra ai tuoi nemici e farsi sollevare dalla corda che lo sosteneva",
	"L\'Ex presidente George W  Bush",
	"Nudità completa",
	"Iniezioni ormonali",
	"Covare un uovo",
	"Spogliarsi e mettersi a guardare l\'Albero Azzurro",
	"Far finta di interessarsi",
	"Ridicolizzarsi in pubblico",
	"Scambiarsi le siringhe",
	"Caccole",
	"L\'inevitabile morte termica dell\'universo",
	"Il miracolo della nascita",
	"Il rapimento alieno",
	"Tirarlo fuori",
	"I privilegi dei bianchi",
	"Compiti da moglie",
	"La banda Bassotti",
	"Deodorante AXE",
	"Il sangue di Cristo",
	"Orribili incidenti dovuti alla depilazione laser",
	"BATMAN!!! ",
	"Agricoltura",
	"Un robusto mongoloide",
	"Selezione naturale",
	"Aborti fatti con l\'appendiabiti",
	"Mangiarsi tutti  i dolci prima  dell\'inizio  della cena di beneficenza per i malati di AIDS",
	"Le braccia di Michelle Obama",
	"World of Warcraft",
	"Andare in picchiata",
	"Obesità",
	"Un montaggio pallavolistico omoerotico",
	"Tetano",
	"Una dimostrazione di un accoppiamento",
	"Torsione del testicolo",
	"Cena a buffet per 5 euro",
	"Pizza con la nutella",
	"Gigi D\'Alessio",
	"Formaggio piccante",
	"Attacchi da Velociraptor",
	"Togliersi la maglietta",
	"Smegma",
	"Alcolismo",
	"Un uomo di mezza eta\' con un paio di pattini in linea",
	"Lo sguardo fisso di una Winx",
	"Abbuffarsi e vomitare",
	"Lecca-Lecca giganti",
	"Disgusto di sé",
	"Bambini al guinzaglio",
	"Preliminari meschini",
	"La sacra Bibbia",
	"Porno in un sotterraneo tedesco",
	"Essere in fiamme",
	"Gravidanza in età adolescenziale",
	"Gandhi",
	"Lasciare un messaggio imbarazzante in segreteria",
	"Montanti",
	"Agente del servizio clienti",
	"Un\'erezione che dura più di quattro ore",
	"I miei genitali",
	"Rimorchiare ragazze all\'ospedale dopo un aborto",
	"Scienza",
	"Sesso orale non ricambiato",
	"Uccelli incapaci di volare",
	"Una buona sniffata",
	"Tortura cinese",
	"Una colazione bilanciata",
	"Scuole gestite da suore",
	"Rubare veramente una caramella ad un bambino",
	"La fondazione Make-A-Wish",
	"Una grattata di culo clandestina",
	"Post-it passivi aggressivi",
	"La squadra di ginnastica artistica cinese",
	"Passare a Vodafone",
	"Fare solo un pochino di pipì",
	"Video di Barbara D\'Urso in lacrime mentre ascolta una storia triste",
	"Polluzione notturna",
	"Gli ebrei",
	"Le mie tette",
	"Cosce poderose",
	"Fare I\'occhioIino a persone anziane",
	"Mr  Muscolo, giusto dietro di te",
	"Una gentile carezza nell\'interno della coscia",
	"Tensione sessuale",
	"Il frutto proibito",
	"Skeletor",
	"KiteKat",
	"Essere ricco",
	"Dolce, dolce vendetta",
	"Popolo delle Libertà",
	"Centauri",
	"Un\'antiIope che soffre di flatulenza",
	"Natalie Portman",
	"Toccare una tetta senza dare nell\'occhio",
	"Piloti Kamikaze",
	"Sean Connery",
	"Obbiettivi politici degli omosessuali",
	"Un operoso cinese",
	"Un falco con un cappuccio in testa",
	"Chierichetti",
	"Pac--Man",
	"Diventare così arrabbiati da farsi venire un\'erezione",
	"Campioni gratuiti",
	"Un gran rumore per nulla",
	"Fare la cosa giusta",
	"I patti Lateranensi",
	"Allattamento",
	"La pace nel mondo",
	"RoboCop",
	"Faccia tosta",
	"Justin Bieber",
	"Oompa-Loompa",
	"Gorgheggi in momenti inappropriati",
	"Pubertà",
	"Fantasmi",
	"Una spagnola non simmetrica",
	"Mani vigorose da jazzista",
	"Ditalini",
	"Bruno Vespa che si impiglia con lo scroto in un gancio per le tende",
	"Polaretti",
	"Violenza della polizia",
	"Totò Riina",
	"Preadolescente",
	"Scalpare",
	"Mascherare una risata quando vengono menzionati gli Hutu e i Tutsi",
	"Twittare",
	"Darth Fenner",
	"Una pugnetta triste",
	"Esattamente quello che ti aspetti",
	"Aspettarsi un rutto e invece vomitare sul pavimento",
	"Psicofarmaci",
	"Cellule staminali embrionali",
	"Un succulento seno",
	"Sesso tra panda",
	"Una Iobotomia fatta con un punteruolo",
	"Tom Cruise",
	"Herpes labiale",
	"Capodogli",
	"Barboni",
	"Petting duro",
	"Incesto",
	"Pac-Man che trangugia sperma",
	"Un mimo che ha un infarto",
	"Hulk Hogan",
	"Dio",
	"Esfoliarsi la pelle sotto i rotoli di grasso",
	"Doccia di piscio",
	"Emozioni",
	"Leccare cose per rivendicarle come proprie",
	"Birra Moretti",
	"La placenta",
	"Combustione umana spontanea",
	"Scopamici",
	"Dipingere con le dita",
	"L\'odore delle persone vecchie",
	"Avere soltanto un pollo di gomma con una carrucola in mezzo",
	"I miei demoni interiori",
	"Un Liquidator pieno di piscio di gatto",
	"Giuseppe Mazzini",
	"Coccolarsi",
	"Rosso relativo",
	"Combattimenti tra galli",
	"Fuoco amico",
	"Ronald Reagan",
	"Un compleanno deludente",
	"Una sfacciata donna di colore",
	"Ragazzini che partecipano alle olimpiadi della matematica",
	"Un minuscolo cavallo",
	"Diego Abatantuono",
	"Cavalcare al tramonto",
	"Un colpo di scena degno di",
	"M Night Shyamalan",
	"Dredlock",
	"Distruzione reciproca",
	"Pedofili",
	"Lievito",
	"Saccheggiare tombe",
	"Mangiare I\'ultimo bisonte",
	"Catapulte",
	"Persone povere",
	"Il nome della rosa",
	"Hustle — I signori della truffa",
	"La forza",
	"Pulirle il culo",
	"Creazionismo",
	"Bocca larga",
	"AIDS",
	"Foto di tette",
	"Il superuomo",
	"Sarah Palin",
	"Giochi senza frontiere",
	"Sballarsi",
	"Scientology",
	"L\'invidia per il pene",
	"Curare l\'omosessualità pregando",
	"Spassarsela",
	"Due nani che stanno cagando in un secchio",
	"Il KKK",
	"Gengis Khan",
	"Cristalli di metanfetamina",
	"Servi della gleba",
	"Il pericolo degli sconosciuti",
	"Bop it",
	"La carriera di attore di Shaquille O\'NeaI",
	"Baldanzoso",
	"La giustizia spicciola",
	"Un bukkake censurato",
	"Una vita di tristezza",
	"Razzismo",
	"Lancio dei nani",
	"Sole e arcobaleni",
	"Una scimmia che fuma un sigaro",
	"Inondazione improvvisa",
	"Il testicolo mancante di Lance Armstrong",
	"Conati di vomito",
	"I terroristi",
	"Britney Spears a 55 anni",
	"Atteggiamento",
	"Entrare a canzone iniziata e mettersi a ballare selvaggiamente",
	"Lebbra",
	"Gloryholes",
	"Lame nei capezzoli",
	"Il cuore di un bambino",
	"Cuccioli!",
	"Svegliarsi mezzo nudo nel parcheggio di un McDonald",
	"Dighe dentali",
	"La vagina di Oriana Fallaci",
	"Il perineo",
	"Ascolto interessato",
	"Pulizia etnica",
	"Il brutto anatroccolo",
	"La mano invisibile",
	"Aspettare fino al matrimonio",
	"Stupidita\' incomprensibile",
	"Euphoria di Calvin Klein",
	"Riciclare regali",
	"Disfunzione erettile",
	"Sovra-compensazione",
	"Auto-cannibalismo",
	"La mia collezione di giocattoli erotici high-tech",
	"Il Papa",
	"Le persone non di colore",
	"Porno Tentacolari",
	"Giuliano Ferrara che vomita convulsamente mentre una nidiata di granchi-ragno si schiude nel suo cervello e fuoriesce dai suoi condotti lacrimali",
	"Troppo gel per capelli",
	"Seppuku",
	"Ballare su ghiaccio con persone dello stesso sesso",
	"Barare alle Paraolimpiadi",
	"Carisma",
	"Keanu Reeves",
	"Dario Argento",
	"Nickelback",
	"Una rapida occhiata",
	"Cagarsi l\'anima",
	"Bambini con il cancro al culo",
	"Una sorpresa salata",
	"Il sud",
	"La violazione dei nostri diritti umani basilari",
	"DEVI COSTRUIRE ALTRI PILONI",
	"Stupro su appuntamento",
	"Essere fantastici",
	"Necrofilia",
	"Super Quark",
	"Le persone di colore",
	"Codice cavalleresco",
	"Lunchables",
	"Stronze",
	"Le persone totalmente handicappate",
	"Orfani commoventi",
	"Hitler",
	"Cacca che fa bruciare il culo",
	"Un altro dannato film sui vampiri",
	"Molle Slinky attorcigliate",
	"Il vero significato del Natale",
	"Estrogeni",
	"Un\'aspra marmellata per colazione",
	"Quella cosa che dà la scossa agli addominali",
	"Espellere un calcolo renale",
	"Un buco del culo sbiancato",
	"Michael Jackson",
	"Impianti cibernetici",
	"Ragazzi che non telefonano",
	"Untori",
	"Masturbazione",
	"Allusione sul ceto sociale",
	"Flato vaginale",
	"Nascondere un\'erezione",
	"Intimo commestibile",
	"Viagra",
	"Zuppa che è troppo calda",
	"Maometto",
	"Sesso a sorpresa! ",
	"Mac",
	"Bere da solo",
	"Dita a forma di cazzo",
	"Ferite da arma da taglio multiple",
	"Farsela addosso",
	"Abusi infantili",
	"Palline anali",
	"Morti civili",
	"Salto della quaglia",
	"Christian De Sica",
	"Carne di cavallo",
	"Un cappello davvero alla moda",
	"Kim Jong-il",
	"Peli pubici sul bordo del cesso",
	"Testimoni di Geova",
	"Discriminazione politica",
	"Farlo dall\'entrata posteriore",
	"Imboccare Platinette",
	"Insegnare a un robot ad amare",
	"Un mare di guai",
	"Un mulino a vento pieno di cadaveri",
	"La tigre dei KeIIogg\'s",
	"Indossare la biancheria al contrario per evitare di lavarla",
	"Un raggio della morte",
	"Il soffitto di vetro",
	"Un frigorifero pieno di organi",
	"Il sogno americano",
	"Bere un barile di birra a testa in giù",
	"Quando scoreggi ma ti esce anche una sgommata",
	"Rimangiarsi quello che si è detto",
	"Neonati morti",
	"Prepuzio",
	"Assoli di Sassofoni",
	"Americani",
	"Un feto",
	"Sparare fucilate al cielo mentre stai penetrando fino alle palle un cinghiale urlante",
	"Giorgio Napolitano",
	"Mutilati",
	"Eugenetica",
	"La mia situazione sentimentale",
	"Christopher Walken",
	"Api?",
	"Harry Potter erotica",
	"Scuole Superiori",
	"Sbronzarsi di collutorio",
	"Nazisti",
	"1 kg di eroina Messicana di scarsa qualità",
	"Stephen Hawking che parla sporco",
	"Genitori morti",
	"Permanenza degli oggetti nella sviluppo cognitivo",
	"Pollici opponibili",
	"Test di intelligenza con domande razziste",
	"Parlare a vanvera",
	"Motoseghe al posto delle mani",
	"Nicolas Cage",
	"Una sfilata di bellezza per bambini",
	"Esplosioni",
	"Sniffare colla",
	"Bruno Vespa molestato da uno stormo di avvoltoi",
	"Repressione",
	"Rufis",
	"La mia vagina",
	"Pantaloni da cowboy senza sedere",
	"Psyco",
	"Dare il 110\%",
	"Sua altezza reale, regina Elisabetta ll",
	"I Rhapsody of Fire",
	"Essere tenuto in disparte",
	"Goblin",
	"Speranza",
	"Martin Luther King",
	"Un micropene",
	"La mia anima",
	"Un\'orgia",
	"Vichinghi",
	"Persone eccitanti",
	"Seduzione",
	"Il complesso di Edipo",
	"Oche",
	"Riscaldamento globale",
	"Musica New Age",
	"Scaldamani tascabili",
	"Fare il labbrino",
	"Omicidio mediante veicolo a motore",
	"Suffragio femminile",
	"Un profilattico difettoso",
	"Forum",
	"Bambini africani",
	"Massacro di Utoya in Norvegia",
	"Barack Obama",
	"Asiatici che non sono bravi in matematica",
	"Anziani uomini giapponesi",
	"Scambiarsi battute divertenti",
	"Coppie omosessuali",
	"Dividere le acque del Mar Rosso",
	"Arnold Schwarzenegger",
	"Pompino alla guida",
	"Addominali spettacolari",
	"Panettone",
	"Un leone depresso",
	"Un sacchetto di fagioli magici",
	"Scelte di vita sbagliate",
	"La mia vita sessuale",
	"Auschwitz",
	"Una tartaruga alligatore che ti sta mordendo la punta del pene",
	"Una detonazione termonucleare",
	"Il clitoride",
	"II Big Bang",
	"Mine antiuomo",
	"Amici che si mangiano tutti i salatini",
	"Capre che si stanno mangiando lattine",
	"Lo Schiaccianoci: La danza della Fata Cofanetto",
	"Farsi una sega in una piscina di lacrime di bambini",
	"Flauto a pelle",
	"Il mio momento",
	"La metropolitana",
	"Battute fuori luogo sull\'olocausto",
	"Un mare di guai",
	"Fantasie di un taglialegna",
	"Voce di Morgan Freeman",
	"Donne nelle pubblicità di yogurt",
	"Metodo naturale di allungamento del pene",
	"Essere un fottuto stregone",
	"Piercing nei genitali",
	"Travestiti passabili",
	"Combattimenti sexy con i cuscini",
	"Palle",
	"Nonna",
	"Attrito",
	"Rompicoglioni",
	"Scoreggiare e andarsene via",
	"Essere uno stronzo con i bambini",
	"Installare, in casa, trappole esplosive per ostacolare i ladri",
	"Sistema Oasi Tecnologica del Riposo materassi Eminflex",
	"Morire",
	"L\'uragano Katrina",
	"I gay",
	"La follia di un uomo",
	"Uomini",
	"Gli Amish",
	"Uova di pterodattilo",
	"Esercizi di ``costruzione del gruppo\'\'",
	"Un tumore al cervello",
	"Carte contro l\'umanità",
	"Aver paura di se stesso",
	"Lady Gaga",
	"L\'uomo del latte",
	"Essere sboccati",
	"Mestruazioni",
	"Scaccolarsi con l\'alluce del piede sinistro.",
	"Avere peli pubici fra i denti.",
	];
}

function exp1White(){
	return[
	"Bomba Atomica.",
	"The Big Bang Theory.",
	"Pulire un water incrostato, in un autogrill nel napoletano.",
	"Tatuaggio sbagliato.",
	"Martello Pneumatico.",
	"Cavallo Pazzo.",
	"Cicciolina nuda.",
	"Sheldon Cooper.",
	"BAZINGA!!",
	"Si trasforma in un razzo missile.",
	"Uscimmo a riveder le stelle.",
	"Giovanni Verga.",
	"Poliziotti senza pantaloni con grossi problemi di igiene personale.",
	"Un\'orda famelica di napoletani che non hanno pagato il grattino e vogliono il pizzo!",
	"Aver paura dei vicoli bui mentre cammini per strada con addosso soltanto un impermeabile rosa.",
	"Tarapia tapioco come se fosse antani con la supercazzola prematurata, con lo scappellamento a destra.",
	"Un panino col prosciutto.",
	"Organizzare cene eleganti per scopi professionali.",
	"Simulare un orgasmo gridando come una capra affamata.",
	"Una Peroni sudata.",
	"La nipote di Mubarack.",
	"Un vaffanculo a colazione è quello che ci vuole.",
	"Ho stato io.",
	"Il celodurismo bossiano.",
	"Scorreggiare nell\'ascensore affollato e guardare schifato quello accanto. ",
	"Volere la botte piena, la moglie ubriaca e un cazzo in culo.",
	"Un milione per gli organizzatori, dieci per la questura.",
	"Dormire a quattro di spade come non ci fosse un domani.",
	"Cose che voi umani non potete nemmeno immaginare.",
	"Mangiare il ben di Dio e cagare l\'opera del diavolo.",
	"Diabolico nell\'amplesso, sproporzionato per quel che riguarda le dimensioni del sesso.",
	"Il generatore di fusione che dà energia ai tempo-circuiti e al flusso canalizzatore.",
	"Schiacciare i ricci con il culo.",
	"Ascoltare Marco Masini durante un giro alla Roulette Russa.",
	"Travestirsi da puttanone da competizione.",
	"Pierluca Scaccolarsi al semaforo e dire al venditore che non voglio i fazzoletti.",
	"Fare i gargarismi con il cemento liquido a presa rapida.",
	"Controllare le sgommate nelle mutande.",
	"Fare una puzza ed incolpare il cane.",
	"Dire,appena svegli, buongiorno Aaamore aspirando la A per 3 sec.",
	"Autopsicanalisi.",
	"La crisi economica.",
	"L\'ascella maleodorante.",
	"Vendere la verginità su ebay.",
	"Truccarsi come Moira Orfei.",
	"Guidare a fari spenti nella notte per vedere, se poi è tanto difficile morire.",
	"Perché tutto attaccato si scrive staccato mentre staccato si scrive tutto attaccato?",
	"Essere inculato con veemenza, senza vasellina e con la sabbia da un nero mastodontico.",
	"William Wallace in una spiaggia di nudisti",
	"Obi Wan Kenobi che simula una pugnetta con la spada laser",
	"La mamma di Stifler",
	"Fare economia comprando la carta igienica ruvida",
	"Salto della quaglia",
	"Video porno di Belen",
	"Mutande piene di sabbia [della lettiera del gatto]",
	"Peli pubici di sconosciuti",
	"Saponette fatte con grasso umano",
	"Pianta di ficus, simbolo del potere",
	"Cotton fioc usati",
	"L\'occhio di Sauron con la congiuntivite",
	"Un caffè corretto con del pessimo piscio di cane",
	"Riaccendersi il mozzicone di una sigaretta trovata per terra",
	"L\'insistente signorina che ti propone di cambiare piano telefonico",
	"Scorreggiare così tanto da far scattare l\'allarme antigas.",
	"Scaccolarsi il naso ed essere scoperti.",
	"Cristiano Malgioglio.",
	"Toccarsi i genitali senza farsi vedere.",
	"Sculacciata.",
	"Uomini nudi che fanno l\'elicottero.",
	"Marshmallows avvelenati.",
	"Il 69.",
	"La versione porno dei Simpsons.",
	"Squali volanti.",
	"Fare piedino alla persona sbagliata.",
	"Fare un rutto mentre si recita la poesia di Natale.",
	"Suocera rompipalle.",
	"Sbagliare DVD e far partire un porno.",
	"Vecchietti che guardano lavori in corso con le braccia dietro la schiena.",
	"Una collezione di porno con protagonisti nani ben dotati.",
	"Blue screen of death",
	"La pipì che scappa appena usciti di casa",
	"Un cane che lecca il gelato spalmato sulle tue palle.",
	"Il funerale di Nietzsche.",
	"Un quadro dipinto da una scimmia con le emorroidi.",
	"Annusare il culo ai passanti credendosi un cane.",
	"Pulizia Etnica.",
	"WikiLeaks.",
	"Essere controllati dagli USA tramite l\'NSA.",
	"Agenti FBI che si comportano come checche isteriche.",
	"Mettere il dito nel culo di pikachu e prendere la scossa.",
	"Fingere un malessere per non rispondere ad una domanda",
	"Diventare invisibile e fare scherzi sconci alle ragazze negli spogliatoi delle piscine comunali, mentre il vescovo è in visita alla struttura.",
	"Bambole voodoo.",
	"Acconciarsi i capelli con letame di cavallo.",
	"Sfidarsi a una gara di lancio di bocce incendiarie.",
	"Un nuovo sistema di allungamento del pene.",
	"Farsi un piercing ai genitali con una sparachiodi.",
	"Porno acrobatico.",
	"Un rutto da Coppa dei Campioni.",
	"Gare di rutti.",
	"Apparire come guest star nel nuovo video di Gemmadelsud.",
	"Infilarsi un ravanello nel culo.",
	"Mangiare teste umane.",
	"Tingersi il pube a righe bianche e rosa.",
	"Brucare.",
	"Autoerotismo.",
	"Action Man.",
	"Entrare in una chiesa urlando di essere l\'Anticristo.",
	"Pollo di gomma con carrucola.",
	"Uno svizzero, un francese, un tedesco e un\'italiano.",
	"L\'uomo saggio ama usare l\'ombrello quando piove!",
	"L\'uomo coraggioso ama sentire la natura sulla pelle.",
	"Ho visto cose che voi umani non potreste immaginare...",
	"BitTorrent",
	"Riso Patate e Cozze.",
	"Voglio Godere!!!",
	"Un mondo di dolore!",
	"Finchè c\'è vita c\'è speranza.",
	"Ferrari FF",
	"Qui e lì, notte e dì, questo il mondo fa girar.",
	"Fiamme torreggianti.",
	"Sono il conducente del treno di cacca!",
	"A Kuala Lumpur nel quartiere dei ladyboy.",
	"Navi da combattimento in fiamme al largo dei bastioni di Orione e raggi B balenare nel buio vicino alle porte di Tannhauser.",
	"Un Tandem.",
	"La pillola del giorno dopo.",
	"Al mio via scatenate l\'inferno!",
	"Drag queen.",
	"Acido Acetilsalicilico.",
	"Il gatto di Schrodinger.",
	"La Sirenetta di Copenaghen.",
	"Un Clochard.",
	"Vita morte e miracoli.",
	"Supercalifragilistichespiralidoso.",
	"Il Jolly Roger.",
	"Uno alla testa ed uno al cuore.",
	"Il K2.",
	"Bevo il the a testa in giù usando i piedi.",
	"L\'aiuto del pubblico.",
	"Matitina IKEA.",
	"Dieta mediterranea.",
	"Tre Metri Sopra il Cielo.",
	"Jessica Fletcher.",
	"Fughe di gas.",
	"Evadere il canone RAI.",
	"Alice nel Paese delle Pornomeraviglie.",
	"Un tristissimo film Bielorusso.",
	"Adolescenti arrapati.",
	"Bombardamenti indiscriminati.",
	"L\'ennesima canzone neomelodica napoletana.",
	"Reggere la candela.",
	"Mirabolanti cadute da tacco 12!",
	"Il Colonnello Giuliacci.",
	"Milf estremamente espansive!",
	"Sindrome di Down",
	"PornoStar con desideri sessuali per il proprio padre",
	"Comprare due banane per mangiarne almeno una",
	"Immigrati clandestini",
	"Cowboy gay che mangiano budino",
	"Ascelle puzzolenti",
	"Un ninja con una diarrea incontrollabile",
	"Un culo grasso in pantaloni da yoga",
	"Usare poco lubrificante",
	"Un seno così floscio che le arriva alle ginocchia",
	"Un travestito",
	"Cercatore d\'oro",
	"Scrivere un sms alla propria EX mentre si è ubriachi di vodka",
	"Una Death Race tra sedie a rotelle",
	"Un aborto fallito.",
	"Realizzare che è finita la carta igenica quando ormai è troppo tardi",
	"Una tanadi tigri del bengala affamate.",
	"Macchie non identificabili sulla punta del pene.",
	"Capelli nello scarico della doccia.",
	"Botulino.",
	"Anoressia.",
	"Lupus.",
	"Doctor House.",
	"Schiavitù.",
	"Spada Laser.",
	"Feci spalmate sulla parete del bagno.",
	"Pirati inesperti.",
	"Allergia ai Preservativi.",
	"Guardare un porno in pubblico sull\'iPad a tutto volume.",
	"Facebook.",
	"Una pellicola in Super-8 della prima GangBang della nonna.",
	"M2O",
	"Test della gravidanza.",
	"GloryHole.",
	"Kim Jong Un.",
	"Anime Hentai.",
	"Penny!? Penny!? Penny!?",
	"Un negro di origine asiatica.",
	"Dolore da emorroidi.",
	"Necromanzia.",
	"Massaggiatrici cinesi molto esperte.",
	"Traffico d\'organi.",
	"Lavoro sottopagato.",
	"Riportare in vita i morti.",
	"Vendere organi umani a basso costo e con scarse garanzie igeniche.",
	"Epatite C contratta mangiando cozze crude.",
	"Lenti a contatto a raggi X.",
	"Ridere a crepapelle per nascondere una sonora puzza.",
	"Palpatina furtiva.",
	"Orsi polari che ballano il dadaumpa.",
	"Un pappagallo che dice cose sconce.",
	"Isabella.",
	"Animali domestici guardoni.",
	"Gattini ninja.",
	"Crisi di mezza età.",
	"Un superdotato.",
	"L\'uomo tigre.",
	"Un palestrato con micropene.",
	"Primo bacio con l\'alito di aglio.",
	"Uno spinello.",
	"Bicicletta senza sellino.",
	"Pensare di stare per saltare su un bel tronco e finire in una merda di vacca.",
	"Un hippie che si è appena fatto di LSD.",
	"Scroto.",
	"Vomitare a denti stretti per sentire i pezzettoni.",
	"Avere peli pubici fra i denti.",
	];
}

exports.getDeck = getDeck;
